### ISSUE TITLE
Very Cool!  Thoughts on Rx.NET Integration?

### ISSUE THREAD

**Issue by Mike-E-angelo** [azure-cat-emea/servicefabricobserver#1]
This is a really great demo!  Thank you for putting this together.

I am new to Observable/Rx and have been studying it lately.  Looking through the code, it seems that you are making use of event handlers and Tasks... I was curious if you could comment on your thinking around this and also your thoughts with Rx.  From what I understand, Observable/Rx is meant to compliment event handlers by making them easier to work with, while also helping out with some of their drawbacks.  The same can be said for async/await/Task as well.

Video here for some context:
https://www.youtube.com/watch?v=5DZ8nC0ENdg

Courtesy of the Rx Gitter when I was poking around Reactive. :smile:

Thanks again for putting this together.  Looking forward to diving into this, and also with Service Fabric in general. :+1:

**Comment by paolosalvatori** [comment]
Hi Mike
I started to use Rx years ago and yes, it's very cool piece of the technology. However, I didn't want to take a dependency on it :) Said that, maybe I could refactor the code to use Reactive Extensions in the future... who knows :)
Ciao
Paolo

**Comment by Mike-E-angelo** [comment]
Cool!  Yes, I am just learning it now.  Late to the party. :)  Looks like they are about to release 3.0 soon.  Exciting times, as always!  Haha.  Thank you for your reply, @paolosalvatori!
